In [2]:
#pip install geopandas

In [3]:
import geopandas as gpd
import pandas as pd
import re
import json

In [4]:
zillow_df = pd.read_csv('zillow_home_values.csv')

In [5]:
zillow_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,1996-01-31,...,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31
0,3101,0,Los Angeles County,County,CA,CA,Los Angeles-Long Beach-Anaheim,6,37,177774.0,...,659773.0,664580.0,666444.0,667704.0,672758.0,680207.0,688570.0,695441.0,702046.0,708045.0
1,139,1,Cook County,County,IL,IL,Chicago-Naperville-Elgin,17,31,154331.0,...,253684.0,254076.0,254595.0,255333.0,256710.0,258486.0,261016.0,263754.0,266201.0,268475.0
2,1090,2,Harris County,County,TX,TX,Houston-The Woodlands-Sugar Land,48,201,99675.0,...,199807.0,200940.0,201912.0,202637.0,203555.0,204670.0,206514.0,208295.0,210494.0,212658.0
3,2402,3,Maricopa County,County,AZ,AZ,Phoenix-Mesa-Scottsdale,4,13,116247.0,...,299209.0,302766.0,305996.0,309005.0,311980.0,315932.0,320662.0,325809.0,331342.0,337118.0
4,2841,4,San Diego County,County,CA,CA,San Diego-Carlsbad,6,73,180788.0,...,615413.0,618539.0,622620.0,625616.0,629734.0,636244.0,645855.0,656702.0,667613.0,678665.0

In [7]:
zillow_gdf = gpd.GeoDataFrame(zillow_df.copy())
zillow_gdf.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,1996-01-31,...,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31
0,3101,0,Los Angeles County,County,CA,CA,Los Angeles-Long Beach-Anaheim,6,37,177774.0,...,659773.0,664580.0,666444.0,667704.0,672758.0,680207.0,688570.0,695441.0,702046.0,708045.0
1,139,1,Cook County,County,IL,IL,Chicago-Naperville-Elgin,17,31,154331.0,...,253684.0,254076.0,254595.0,255333.0,256710.0,258486.0,261016.0,263754.0,266201.0,268475.0
2,1090,2,Harris County,County,TX,TX,Houston-The Woodlands-Sugar Land,48,201,99675.0,...,199807.0,200940.0,201912.0,202637.0,203555.0,204670.0,206514.0,208295.0,210494.0,212658.0
3,2402,3,Maricopa County,County,AZ,AZ,Phoenix-Mesa-Scottsdale,4,13,116247.0,...,299209.0,302766.0,305996.0,309005.0,311980.0,315932.0,320662.0,325809.0,331342.0,337118.0
4,2841,4,San Diego County,County,CA,CA,San Diego-Carlsbad,6,73,180788.0,...,615413.0,618539.0,622620.0,625616.0,629734.0,636244.0,645855.0,656702.0,667613.0,678665.0

In [ ]:
with open('geocounty.geojson') as geojsonfile:
    county_json = json.load(geojsonfile)

In [15]:
county_gdf = gpd.read_file("us-county-boundaries.geojson")
county_gdf.head()

,intptlat,countyfp_nozero,name,funcstat,intptlon,lsad,stusab,classfp,awater,countyfp,...,aland,countyns,mtfcc,namelsad,statefp,state_name,cbsafp,csafp,metdivfp,geometry
0,+35.8570011,137,Stone,A,-092.1404819,06,AR,H1,7842161,137,...,1570754768,00069902,G4020,Stone County,05,Arkansas,None,None,None,"POLYGON ((-92.41528 35.86091, -92.41513 35.866..."
1,+39.5377097,1,Churchill,A,-118.2641661,06,NV,H1,190748448,001,...,12821785223,00858638,G4020,Churchill County,32,Nevada,21980,None,None,"POLYGON ((-119.08928 39.60529, -119.08927 39.6..."
2,+41.4330028,7,Middlesex,N,-072.5227802,06,CT,H4,180679140,007,...,956493754,00212797,G4020,Middlesex County,09,Connecticut,25540,278,None,"POLYGON ((-72.65367 41.43812, -72.65419 41.438..."
3,+39.7835420,39,Decatur,A,-100.4597084,06,KS,H1,1631670,039,...,2314199329,00484989,G4020,Decatur County,20,Kansas,None,None,None,"POLYGON ((-100.74044 39.82856, -100.74046 39.8..."
4,+39.6249458,115,Morgan,A,-081.8616967,06,OH,H1,13868572,115,...,1078538278,01074070,G4020,Morgan County,39,Ohio,None,None,None,"POLYGON ((-82.03198 39.63773, -82.03197 39.637..."

In [16]:
print(f'GeoJSON {len(county_gdf)}')
print(f'Zillow {len(zillow_gdf)}')

GeoJSON 3233
Zillow 2859

In [17]:
# merged_geojson = zillow_gdf.merge(county_gdf, left_on=['RegionName','State'], right_on=['namelsad','stusab'])
merged_geojson = county_gdf.merge(zillow_gdf, left_on=['RegionName','State'], right_on=['namelsad','stusab'], how='left')

# @VERA: Search for null columns in the zillow columns to identify non-matches

In [18]:
print(f'Merged Zillow w/ GeoJSON {len(merged_geojson)}')

Merged Zillow w/ GeoJSON 2774

In [19]:
merged_geojson.to_file("zillow_with_county.geojson", driver='GeoJSON')

In [20]:
merged_geojson.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,1996-01-31,...,aland,countyns,mtfcc,namelsad,statefp,state_name,cbsafp,csafp,metdivfp,geometry
0,3101,0,Los Angeles County,County,CA,CA,Los Angeles-Long Beach-Anaheim,6,37,177774.0,...,10511861492,00277283,G4020,Los Angeles County,06,California,31080,348,31084,"MULTIPOLYGON (((-118.70339 34.16859, -118.7033..."
1,139,1,Cook County,County,IL,IL,Chicago-Naperville-Elgin,17,31,154331.0,...,2447357982,01784766,G4020,Cook County,17,Illinois,16980,176,16984,"POLYGON ((-88.23819 42.06699, -88.23819 42.067..."
2,1090,2,Harris County,County,TX,TX,Houston-The Woodlands-Sugar Land,48,201,99675.0,...,4418909573,01383886,G4020,Harris County,48,Texas,26420,288,None,"POLYGON ((-95.85685 29.87458, -95.85686 29.874..."
3,2402,3,Maricopa County,County,AZ,AZ,Phoenix-Mesa-Scottsdale,4,13,116247.0,...,23829622328,00037026,G4020,Maricopa County,04,Arizona,38060,429,None,"POLYGON ((-112.27604 33.88231, -112.27667 33.8..."
4,2841,4,San Diego County,County,CA,CA,San Diego-Carlsbad,6,73,180788.0,...,10904373558,00277301,G4020,San Diego County,06,California,41740,None,None,"POLYGON ((-117.43743 33.17953, -117.44954 33.1..."